import { afterEach, describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { createGame, readSave, SAVE_KEY } from '../helpers/game.js';

// Phase 0 — characterization of the legacy game (app.js) BEFORE the refactor.
// These tests are the "oracle": they must keep passing after every port phase
// (retargeted to src/core/save.ts in Phase 2). PLAN rule: applySave() must keep
// accepting schema v1 forever.
//
// OBSERVED SAVE BEHAVIOR (discovered by these tests, not guessed):
//  - save() also stores "peek" rows generated by renderMine (rows around/below
//    topRow) — normalize() trims them to rows.length === topRow on load.
//  - The durable core of a save is: every non-rows field + rows[0, topRow).
//  - Rows >= topRow are REGENERATED on every load (gems re-roll, max = HP
//    formula × 2 for gems). Reload is not byte-identical at the frontier —
//    that's how the game always behaved; we pin it instead of pretending.

const fixture = JSON.parse(readFileSync(new URL('./fixtures/save-v1.json', import.meta.url), 'utf8'));
const legacy = JSON.parse(readFileSync(new URL('./fixtures/save-v1-legacy.json', import.meta.url), 'utf8'));

const SCHEMA_V1_KEYS = [
  'coins', 'spawnLvl', 'spawnCost', 'upCost', 'incLvl', 'incCost', 'renLvl', 'renCost',
  'grid', 'rows', 'topRow', 'inv',
  'blastLvl', 'blastCost', 'bombs', 'bombCost',
  'war', 'acc', 'econ', 'skins', 'bestDepth'
];

const COLS = 5;
const VIEW = 5; // app.js: VIEW=5 — renderMine peeks VIEW rows starting at topRow

// Copy of the makeRow() formula — pinned here to guard the core/mine.ts port in Phase 2
const accLvlOf = xp => 1 + Math.floor(Math.sqrt(xp / 40));
const baseHp = (r, accLvl) => Math.max(1, Math.round(2.5 * Math.pow(1.12, r) * (1 + 0.05 * (accLvl - 1))));

/** Freshly makeRow()-generated rows: COLS cells, full HP, max per the formula. */
function expectFreshRows(rows, startRow, accLvl) {
  rows.forEach((row, i) => {
    expect(row, `row ${startRow + i}`).toHaveLength(COLS);
    row.forEach(cell => {
      const base = baseHp(startRow + i, accLvl);
      expect(cell.max, `row ${startRow + i} max`).toBe(cell.gem ? base * 2 : base);
      expect(cell.hp, `row ${startRow + i} hp`).toBe(cell.max); // undamaged = full HP
      expect(typeof cell.gem).toBe('boolean');
    });
  });
}

let open = [];
function boot(opts) {
  const g = createGame(opts);
  open.push(g);
  return g;
}
afterEach(() => { open.forEach(g => g.dom.window.close()); open = []; });

describe('v1 save schema', () => {
  it('save() writes exactly the v1 key set under kopalnia-save-v1', () => {
    const g = boot();
    const saved = g.api.save();
    expect(Object.keys(saved).sort()).toEqual([...SCHEMA_V1_KEYS].sort());
    expect(readSave(g.window)).toEqual(saved);
  });

  it('a fresh game boots with default values', () => {
    const g = boot();
    const s = g.api.save();
    expect(s.coins).toBe(30);
    expect(s.grid).toEqual(Array(25).fill(0));
    expect(s.topRow).toBe(0);
    expect(s.acc).toEqual({ xp: 0, s: { pow: 0, gain: 0, luck: 0, hp: 0 } });
    expect(s.skins).toEqual({ items: [], cur: null, nid: 1 });
    expect(s.bestDepth).toBe(0);
    // renderMine generated VIEW peek rows (rowAt(0..4))
    expect(s.rows).toHaveLength(VIEW);
    expectFreshRows(s.rows, 0, accLvlOf(0));
  });
});

describe('save-v1.json (mid-game fixture)', () => {
  it('game loads the fixture and keeps every non-rows field', () => {
    const g = boot({ save: fixture });
    const s = g.api.save();
    for (const key of SCHEMA_V1_KEYS) {
      if (key === 'rows') continue;
      expect(s[key], `field ${key}`).toEqual(fixture[key]);
    }
  });

  it('rows[0, topRow) is durable — rows >= topRow rebuilt by the HP formula', () => {
    const g = boot({ save: fixture });
    const s = g.api.save();
    expect(fixture.rows.length).toBe(fixture.topRow + 1); // real saves carry 1 peek row
    expect(s.rows.slice(0, fixture.topRow)).toEqual(fixture.rows.slice(0, fixture.topRow)); // core untouched
    expect(s.rows.length).toBe(fixture.topRow + VIEW);    // normalize trimmed, renderMine re-peeked
    expectFreshRows(s.rows.slice(fixture.topRow), fixture.topRow, accLvlOf(fixture.acc.xp));
  });

  it('reload preserves the durable core (fields + rows[0, topRow)) — frontier re-rolled', () => {
    const s1 = boot({ save: fixture }).api.save();
    const s2 = boot({ save: s1 }).api.save();
    for (const key of SCHEMA_V1_KEYS) {
      if (key === 'rows') continue;
      expect(s2[key], `field ${key}`).toEqual(s1[key]);
    }
    expect(s2.rows.slice(0, fixture.topRow)).toEqual(s1.rows.slice(0, fixture.topRow));
    expect(s2.rows).toHaveLength(s1.rows.length);
    expectFreshRows(s2.rows.slice(fixture.topRow), fixture.topRow, accLvlOf(fixture.acc.xp));
  });
});

describe('save-v1-legacy.json (old schema, missing fields)', () => {
  it('missing fields fall back to defaults', () => {
    const g = boot({ save: legacy });
    const s = g.api.save();
    expect(s.blastLvl).toBe(0);
    expect(s.blastCost).toBe(80);
    expect(s.bombs).toBe(0);
    expect(s.bombCost).toBe(250);
    expect(s.econ).toEqual({ pas: 0, dis: 0 });
    expect(s.acc.s).toEqual({ pow: 0, gain: 0, luck: 0, hp: 0 });
    expect(s.bestDepth).toBe(10);        // fields that EXISTED are untouched
    expect(s.coins).toBe(1500);
    expect(s.topRow).toBe(5);
    expect(s.inv).toEqual({ 2: 1 });
    expect(s.war).toEqual({ wave: 2, fire: 0, slow: 0, weak: 0 });
    // "rows" did not exist → rows 0..topRow+VIEW-1 generated from scratch per the formula
    expect(s.rows).toHaveLength(legacy.topRow + VIEW);
    expectFreshRows(s.rows, 0, accLvlOf(legacy.acc.xp));
  });

  it('migrates skins.owned → skins.items (skips "def", maps cur to id)', () => {
    const g = boot({ save: legacy });
    const s = g.api.save();
    expect(s.skins.owned).toBeUndefined();
    expect(s.skins.items.map(({ id, theme, rar }) => ({ id, theme, rar }))).toEqual([
      { id: 1, theme: 'crypto', rar: 0 },
      { id: 2, theme: 'planet', rar: 0 }
    ]);
    expect(s.skins.cur).toBe(2);   // "planet" → id 2
    expect(s.skins.nid).toBe(3);
    // perks are rolled lazily on first use — we pin the shape
    expect(s.skins.items[1].perks).toHaveLength(1);
    expect(['pow', 'gain', 'exp', 'blast', 'fire', 'slow', 'luck']).toContain(s.skins.items[1].perks[0].t);
    expect(s.skins.items[1].perks[0].q).toBeGreaterThanOrEqual(0);
    expect(s.skins.items[1].perks[0].q).toBeLessThanOrEqual(3);
  });

  it('after migration the legacy save core is durable across reloads', () => {
    const s1 = boot({ save: legacy }).api.save();
    const s2 = boot({ save: s1 }).api.save();
    for (const key of SCHEMA_V1_KEYS) {
      if (key === 'rows') continue;
      expect(s2[key], `field ${key}`).toEqual(s1[key]);
    }
    expect(s2.rows.slice(0, legacy.topRow)).toEqual(s1.rows.slice(0, legacy.topRow));
    expect(s2.rows).toHaveLength(s1.rows.length);
    expectFreshRows(s2.rows.slice(legacy.topRow), legacy.topRow, accLvlOf(legacy.acc.xp));
  });
});

describe('robustness', () => {
  it('corrupt JSON in localStorage does not crash the game — boots with defaults', () => {
    const g = boot({ raw: '{"coins": 15, missing-brace' });
    const s = g.api.save();
    expect(s.coins).toBe(30);
    expect(s.grid).toEqual(Array(25).fill(0));
    expect(s.topRow).toBe(0);
  });

  it('normalize() is idempotent (second call changes nothing)', () => {
    const g = boot();
    g.api.normalize();
    const s1 = g.api.save();
    g.api.normalize();
    const s2 = g.api.save();
    expect(s2).toEqual(s1);
  });

  it('missing localStorage key → game boots and saving works', () => {
    const g = boot();
    g.window.localStorage.removeItem(SAVE_KEY);
    g.api.set({ coins: 999 });
    expect(() => g.api.normalize()).not.toThrow();
    const s = g.api.save();
    expect(s.coins).toBe(999);
    expect(readSave(g.window).coins).toBe(999);
  });
});
